# Generated by Django 5.2 on 2025-05-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('oac', 'OAC'), ('farmacia', 'Farmacia'), ('almacen', 'Almacén'), ('none', 'Sin departamento')], default='none', help_text='Departamento al que pertenece el usuario', max_length=10, verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('admin', 'Admin'), ('superAdmin', 'Super Admin'), ('basic', 'Basic')], default='basic', max_length=10, verbose_name='status'),
        ),
    ]
