# Generated by Django 5.2 on 2025-05-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('admin', 'Admin'), ('superAdmin', 'Super Admin'), ('basic', 'Basic'), ('coordinador', 'Coordinador')], default='basic', max_length=15, verbose_name='status'),
        ),
    ]
