/**
 * Constants for form field validation
 */
export const MAX_CODIGO_ARTICULO_LENGTH = 20;
export const MAX_TIPO_INSUMO_LENGTH = 50;
export const MAX_CATEGORIA_LENGTH = 30;
export const MAX_FACTURA_LENGTH = 30;
export const MIN_INVENTARIO = 1;
export const MAX_INVENTARIO = 10000;

/**
 * Enum for article status
 */
export enum ArticleStatus {
  DISPONIBLE = "Disponible",
  EN_USO = "En Uso",
  EN_REPARACION = "En Reparación",
  BAJA = "Baja"
}

/**
 * Categories for articles
 */
export const CATEGORIAS = ["Ayuda Tecnica", "Ayuda Social"];

/**
 * Interface for inventory article
 */
export interface InventoryArticle {
  id: string;
  codigo_articulo: string;
  tipo_insumo: string;
  categoria: string;
  descripcion: string;
  estado: ArticleStatus | string;
  numero_factura: string;
  inventario_total: number;
  inventario_entrega: number;
  fecha_adquisicion: string;
  fecha_mantenimiento?: string;
  
  // Optional fields that might be used in the UI
  created_at?: string;
  updated_at?: string;
}

/**
 * Interface for inventory article creation
 * Omits the ID field which is generated by the server
 */
export type CreateInventoryArticle = Omit<InventoryArticle, "id">;

/**
 * Interface for inventory article update
 * All fields are optional
 */
export type UpdateInventoryArticle = Partial<InventoryArticle>;

/**
 * Interface for inventory summary stats
 */
export interface InventorySummary {
  total_items: number;
  available_items: number;
  delivered_items: number;
  by_category: {
    [key: string]: number;
  };
}

