# Generated by Django 5.2 on 2025-05-27 05:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_articulo', models.CharField(db_column='Codigo_Articulo', default='N/A', max_length=50)),
                ('nombre', models.CharField(db_column='Nombre', default='Sin nombre', max_length=250)),
                ('tipo_insumo', models.CharField(db_column='Tipo_Insumo', default='No especificado', max_length=250)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('estado', models.CharField(db_column='Estado', default='Disponible', max_length=50)),
                ('numero_factura', models.CharField(blank=True, db_column='Numero_Factura', max_length=50, null=True)),
                ('inventario_total', models.IntegerField(db_column='Inventario_Total', default=0)),
                ('inventario_entrega', models.IntegerField(db_column='Inventario_Entrega', default=0)),
                ('fecha_adquisicion', models.DateField(db_column='Fecha_Adquisicion', default=django.utils.timezone.now)),
                ('fecha_mantenimiento', models.DateField(blank=True, db_column='Fecha_Mantenimiento', null=True)),
                ('ubicacion', models.CharField(db_column='Ubicacion', default='Sin ubicación', max_length=250)),
                ('proveedor', models.CharField(db_column='Proveedor', default='Sin proveedor', max_length=250)),
                ('categoria', models.CharField(blank=True, db_column='Categoria', max_length=70, null=True)),
            ],
            options={
                'db_table': 'Inventory',
                'managed': True,
            },
        ),
    ]
