# Generated by Django 5.2 on 2025-05-27 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='proveedor',
        ),
    ]
