# Generated by Django 5.2 on 2025-05-27 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_remove_inventory_nombre_remove_inventory_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='ubicacion',
        ),
    ]
