# Generated by Django 5.2 on 2025-05-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_remove_inventory_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='codigo_articulo',
            field=models.CharField(db_column='Codigo_Articulo', default='N/A', max_length=50, unique=True),
        ),
    ]
